### ISSUE TITLE
Unhandled error in POST /users: 500 MongoError: command insert requires authentication

### ISSUE THREAD

**Issue by bizbi** [strongloop/loopback4-example-shopping#281]
The LB4 shopping example uses no mongo credentials or database name:

{
  "name": "mongo",
  "connector": "mongodb",
  "url": "",
  "host": "127.0.0.1",
  "port": 27017,
  "user": "",
  "password": "",
  "database": "",
  "useNewUrlParser": true
}

For production use, I'm trying to adapt this to a named, secured mongo database:

{
  "name": "mongo",
  "connector": "mongodb",
  "url": "mongodb://userAdminUsername:userAdminPassword@localhost:27017/users",
  "host": "localhost",
  "port": 27017,
  "user": "userAdminUsername",
  "password": "userAdminPassword",
  "database": "users",
  "authSource": "admin",
  "useUnifiedTopology": true,
  "useNewUrlParser": true,
  "useCreateIndex": true,
  "lazyConnect": true,
  "autoReconnect": true,
  "reconnectTries": 50,
  "reconnectInterval": 1000
}

The user "userAdminUsername" was created in the admin database with:

    roles: [ { role: "userAdminAnyDatabase", db: "admin" }, "readWriteAnyDatabase" ]

My user controller is a simplified version of the shopping one, with no orders but all other details and supporting files replicated.  On attempting to create a user, loopback gives the following error:

Unhandled error in POST /users: 500 MongoError: command insert requires authentication
    at Connection.<anonymous> (/mnt/c/src/loopback/node_modules/mongodb/lib/core/connection/pool.js:466:61)
    at Connection.emit (events.js:209:13)
    at processMessage (/mnt/c/src/loopback/node_modules/mongodb/lib/core/connection/connection.js:364:10)
    at Socket.<anonymous> (/mnt/c/src/loopback/node_modules/mongodb/lib/core/connection/connection.js:533:15)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)

Help gratefully received!

**Comment by dhmlau** [comment]
@hacksparrow, could you please take a look? Thanks.

**Comment by bizbi** [comment]
@hacksparrow 

FYI, when I just substitute the new mongo credentials into the shopping app, it works fine.  So the problem is something I've not done (or done wrong) in my existing loopback app when I tried to extend it with authentication as follows:

- Copied in authentication-strategies/jwt-strategy.ts
- Copied in controllers/user.controller.ts and added it to controllers/index.ts
- Copied in controllers/specs/user-controllers.specs.ts
- Updated the mongo datasource as above
- Copied in user.model.ts, stripping out the Order parts (mine is not a shopping app)
- Copied in repositories/user.repository.ts and added it to repositories/index.ts
- Copied in services/hash.password.bcrypt.js, services/jwt-service.ts, services/user-service.ts, and services/validator.ts
- Copied in utils/retry.ts
- Copied in keys.ts and sequence.ts
- Copied in index.ts and application.ts, changing the application name

**Comment by dhmlau** [comment]
Sorry.. I didn't read the description very thoroughly.  Assigning it to @jannyHou @emonddr instead because they're working on the authentication. Thanks.

**Comment by raymondfeng** [comment]
@bizbi Can you try to remove `url` property? It's exclusive with other settings.

**Comment by jannyHou** [comment]
@bizbi 
> Unhandled error in POST /users: 500 MongoError: command insert requires authentication

The log implies error may come from your credentials, the "authentication" above should be the mongodb database's authentication, not from the example's auth system. 

Could you try Raymond's comment in https://github.com/strongloop/loopback4-example-shopping/issues/281#issuecomment-548445180?

And also try remove `"lazyConnect": true,`

**Comment by dhmlau** [comment]
Closing due to inactivity
