### ISSUE TITLE
Dockerize fails with "Can not read file in context"

### ISSUE THREAD

**Issue by bizbi** [strongloop/loopback4-example-shopping#288]
Trying to dockerize this example but it fails with "Can not read file in context".

Any ideas?  Help gratefully received.

docker-compose.yml:

    version: '3'
    services:
      loopback:
        container_name: loopback
        build:
            context: .
        ports:
          - 3000:3000
          - 3001:3001
        restart: always`

Dockerfile:

    FROM node:current-alpine
    
    WORKDIR /usr/src/app
    
    COPY package.json .
    RUN npm install --loglevel notice
    
    COPY packages/recommender ./packages/recommender
    COPY packages/shopping ./packages/shopping
    
    ENV PORT=3000
    ENV TEMP_DIR=/usr/src/app/tmp
    ENV LOG_DIR=/usr/log
    ENV LOG_LEVEL=debug
    ENV NODE_ENV=production
    
    # install and build
    COPY lerna.json .
    RUN lerna bootstrap
    
    EXPOSE 3000 3001
    CMD [ "npm", "start" ]

.dockerignore:

    `# Include
    !/packages/recommender
    !/packages/shopping
    
    # Exclude
    node_modules
    npm-debug.log
    Dockerfile*
    docker-compose*
    .dockerignore
    .git
    .gitignore
    README.md
    LICENSE
    .vscode

Error output:

    Building loopback
    Traceback (most recent call last):
      File "site-packages\docker\utils\build.py", line 96, in create_archive
    OSError: [Errno 22] Invalid argument: '\\\\?    \\C:\\src\\loopback\\packages\\recommender\\node_modules\\.bin\\_mocha'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "docker-compose", line 6, in <module>
      File "compose\cli\main.py", line 71, in main
      File "compose\cli\main.py", line 127, in perform_command
      File "compose\cli\main.py", line 1085, in up
      File "compose\cli\main.py", line 1081, in up
      File "compose\project.py", line 527, in up
      File "compose\service.py", line 360, in ensure_image_exists
      File "compose\service.py", line 1084, in build
      File "site-packages\docker\api\build.py", line 159, in build
      File "site-packages\docker\utils\build.py", line 31, in tar
      File "site-packages\docker\utils\build.py", line 100, in create_archive
    OSError: Can not read file in context: \\?\C:\src\loopback\packages\recommender\node_modules\.bin\_mocha
    [4788] Failed to execute script docker-compose

**Comment by raymondfeng** [comment]
Please follow https://github.com/strongloop/loopback4-example-shopping/pull/268

**Comment by bizbi** [comment]
Thanks @raymondfeng. Closing issue.
