### ISSUE TITLE
npm start throws errors

### ISSUE THREAD

**Issue by PhilippeCorreges** [strongloop/loopback4-example-shopping#386]
Hello,
Nodejs has the correct version : 

npm i is ok.
npm start throws:
npm start

> loopback4-example-shopping-monorepo@1.1.1 prestart /Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping
> npm run build

> loopback4-example-shopping-monorepo@1.1.1 build /Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping
> lerna run build

> loopback4-example-recommender@1.1.1 build /Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping/packages/recommender
> lb-tsc
> loopback4-example-shopping@1.1.1 build /Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping/packages/shopping
> lb-tsc

> loopback4-example-shopping-monorepo@1.1.1 start /Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping
> concurrently --kill-others "npm run start:app" "npm run start:recommender"

[0] 
[0] > loopback4-example-shopping-monorepo@1.1.1 start:app /Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping
[0] > node ./packages/shopping
[0] 
[1] 
[1] > loopback4-example-shopping-monorepo@1.1.1 start:recommender /Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping
[1] > node ./packages/recommender
[1] 
[1] Recommendation REST server is running at http://[::1]:3001.
[1] Recommendation gRPC server is running at 0.0.0.0:50051.
[0] Server is running at http://[::1]:3000
[0] Try http://[::1]:3000/ping
[0] Echec de la connexion : Error: connect ECONNREFUSED 127.0.0.1:6379
[0] Un nouvel essai sera effectué pour la demande suivante.
[0] events.js:174
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: connect ECONNREFUSED 127.0.0.1:6379
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
[0] Emitted 'error' event at:
[0]     at RedisDataSource.postInit (/Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping/packages/shopping/node_modules/loopback-datasource-juggler/lib/datasource.js:500:16)
[0]     at Object.onceWrapper (events.js:277:13)
[0]     at Redis.emit (events.js:189:13)
[0]     at Redis.silentEmit (/Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping/packages/shopping/node_modules/ioredis/built/redis/index.js:489:26)
[0]     at Socket.<anonymous> (/Volumes/Data/Projects/WebStormProjects/loopback4-example-shopping/packages/shopping/node_modules/ioredis/built/redis/event_handler.js:122:14)
[0]     at Object.onceWrapper (events.js:277:13)
[0]     at Socket.emit (events.js:189:13)
[0]     at emitErrorNT (internal/streams/destroy.js:82:8)
[0]     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
[0]     at process._tickCallback (internal/process/next_tick.js:63:19)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! loopback4-example-shopping-monorepo@1.1.1 start:app: `node ./packages/shopping`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the loopback4-example-shopping-monorepo@1.1.1 start:app script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /Users/IOSoftwareSAS/.npm/_logs/2019-11-15T12_15_39_299Z-debug.log
[0] npm run start:app exited with code 1
--> Sending SIGTERM to other processes..
[1] npm run start:recommender exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback4-example-shopping-monorepo@1.1.1 start: `concurrently --kill-others "npm run start:app" "npm run start:recommender"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback4-example-shopping-monorepo@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/IOSoftwareSAS/.npm/_logs/2019-11-15T12_15_39_460Z-debug.log

**Comment by dhmlau** [comment]
@PhilippeCorreges, it looks like your redis docker image is not up because it's complaining about port 6379. Looking at the docs https://loopback.io/doc/en/lb4/Authentication-Tutorial.html#try-it-out, it says:
```
npm install
npm run docker:start
npm start
```

Did you run `npm run docker:start` before `npm start`?

**Comment by PhilippeCorreges** [comment]
hello @dhmlau 
Effectively I did not run **npm run docker:start**. Now it works fine.

Thanks for that.

**Comment by brenly2015** [comment]
> loopback4-example-shopping-monorepo@1.1.1 start:app /home/brenly/www/ucas/loopback4-example-shopping
> node ./packages/shopping

La conexión falla: Error: connect ECONNREFUSED 127.0.0.1:6379
Se reintentará en la siguiente solicitud.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at RedisDataSource.postInit (/home/brenly/www/ucas/loopback4-example-shopping/packages/shopping/node_modules/loopback-datasource-juggler/lib/datasource.js:502:16)
    at Object.onceWrapper (events.js:286:20)
    at Redis.emit (events.js:198:13)
    at Redis.silentEmit (/home/brenly/www/ucas/loopback4-example-shopping/packages/shopping/node_modules/ioredis/built/redis/index.js:489:26)
    at Socket.<anonymous> (/home/brenly/www/ucas/loopback4-example-shopping/packages/shopping/node_modules/ioredis/built/redis/event_handler.js:122:14)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback4-example-shopping-monorepo@1.1.1 start:app: `node ./packages/shopping`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback4-example-shopping-monorepo@1.1.1 start:app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brenly/.npm/_logs/2020-02-20T19_45_08_531Z-debug.log
