### ISSUE TITLE
`npm test` fails with timeout

### ISSUE THREAD

**Issue by v-andrew** [strongloop/loopback4-example-shopping#452]
To reproduce, run the following commands:
- `git clone https://github.com/strongloop/loopback4-example-shopping`
- `cd loopback4-example-shopping`
- `npm install`
- `npm test`

It fails with:
```
> lb-mocha --allow-console-logs "packages/*/dist/__tests__/**/*.js"

  !

0 passing (15ms)
1 failing
1) "before all" hook in "{root}":
Error: connect ENOENT //./pipe/docker_engine
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
npm ERR! Test failed.  See above for more details.
```

**Comment by dougal83** [comment]
Hi Andrew
Do you have [Docker](https://docs.docker.com/install/) installed?

**Comment by dougal83** [comment]
@raymondfeng Hi Raymond, I'm getting the same error below on Win 10 and Ubuntu 19.  Do you have any ideas?

````node
> loopback4-example-shopping-monorepo@1.1.1 test /home/user/dev/loopback4-example-shopping
> lb-mocha --allow-console-logs "packages/*/dist/__tests__/**/*.js"



  !

  0 passing (33s)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)



npm ERR! Test failed.  See above for more details.
````

**Comment by RipkensLar** [comment]
Experiencing the same error.

**Comment by dhmlau** [comment]
I'm using MacOS, and it seems to be working fine for me. @hacksparrow, since you're actively working on this repo, do you have some insights on this? Thanks.

```
> loopback4-example-shopping-monorepo@1.1.1 test /Users/dhmlau/loopback/loopback4-example-shopping
> lb-mocha --allow-console-logs "packages/*/dist/__tests__/**/*.js"



  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․,․,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  66 passing (9s)
  3 pending
```

**Comment by hacksparrow** [comment]
Hard to tell without a Windows machine.

**Comment by dougal83** [comment]
> Hard to tell without a Windows machine.

@hacksparrow Is there anything I can run on Win 10/Ubuntu to give useful diag. info?
If it helps...  https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

@v-andrew I think `Error: connect ENOENT //./pipe/docker_engine` typically means docker is not running.

**Comment by raymondfeng** [comment]
It requires a docker engine to be running on the Windows machine.

**Comment by dougal83** [comment]
Resolved Ubuntu issue, not sure what was wrong but tests now run correctly.  Have completely rebuilt VM with 4Gb RAM instead of 2Gb.

**Comment by RipkensLar** [comment]
It would be good to document and/or update the README.md because the installation instructions do not say anything about Docker. I myself never used Docker and I have no idea what I have to do to get this working.

**Comment by dougal83** [comment]
Working on Win 10 via WSL remote console on VSCode.

```bash
> loopback4-example-shopping-monorepo@1.1.1 test /i/dev/loopback4-example-shopping
> lb-mocha --allow-console-logs "packages/*/dist/__tests__/**/*.js"

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․,․,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  66 passing (14s)
  3 pending
```

Rel: https://github.com/strongloop/loopback-next/issues/4425

**Comment by v-andrew** [comment]
> It requires a docker engine to be running on the Windows machine.

Doesn't work with Docker running

```
> lb-mocha --allow-console-logs "packages/*/dist/__tests__/**/*.js"                                                                                                                                                                                                                                                                                                                                             

  !                                                                                                                                                                                                                                                                                                                                                                                                               0 passing (30s)                                                                                                                                                                                         1 failing                                                                                                                                                                                                                                                                                                                                                                                                       1) "before all" hook in "{root}":                                                                                                                                                                          Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.                                                                    at listOnTimeout (internal/timers.js:531:17)                                                                                                                                                            at processTimers (internal/timers.js:475:7)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
npm ERR! Test failed.  See above for more details.                                              
```

**Comment by dougal83** [comment]
https://github.com/strongloop/loopback-next/issues/4425

**Comment by fishera123** [comment]
Hi, when I run tests, always getting timeout error. 

```
> loopback4-example-shopping-monorepo@1.1.1 test /loopback4-example-shopping
> lb-mocha --allow-console-logs "packages/*/dist/__tests__/**/*.js"
  !
  0 passing (31s)
  1 failing
  1) "before all" hook in "{root}":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```
