### ISSUE TITLE
[17:17:08] E/configParser - Error message: failed loading configuration file conf

### ISSUE THREAD

**Issue by vipul23394** [strongloop/loopback4-example-shopping#496]
[17:17:08] E/configParser - Error code: 105
[17:17:08] E/configParser - Error message: failed loading configuration file conf
[17:17:08] E/configParser - Error: Cannot find module 'C:\Users\Vipul\git\ep1\conf'
Require stack:
- C:\Users\Vipul\git\ep1\Easypolicy\node_modules\protractor\built\configParser.js
- C:\Users\Vipul\git\ep1\Easypolicy\node_modules\protractor\built\launcher.js
- C:\Users\Vipul\git\ep1\Easypolicy\node_modules\protractor\built\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at ConfigParser.addFileConfig (C:\Users\Vipul\git\ep1\Easypolicy\node_modules\protractor\built\configParser.js:135:26)
    at Object.initFn [as init] (C:\Users\Vipul\git\ep1\Easypolicy\node_modules\protractor\built\launcher.js:93:22)
    at Object.<anonymous> (C:\Users\Vipul\git\ep1\Easypolicy\node_modules\protractor\built\cli.js:226:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)

**Comment by dougal83** [comment]
Hi @vipul23394 

Was this posted in error to this repository?  I don't see how this is related.
